services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.17.0
    container_name: artifactory
    networks:
      - ci_net
    ports:
      - 8081:8081
    volumes:
      - artifactory:/var/opt/jfrog/artifactory
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5001:5000
    networks:
    - ci_net
volumes:
  artifactory:
networks:
  ci_net:

